create table structuresdb.dbo.tbl_doitt_structures(fid serial,
												   bin int,
												   base_bbl varchar(10),
												   mappluto_bbl varchar(10),
												   doitt_id int primary key,
												   ground_elevation int,
												   height_roof numeric(38,8),
												   construction_year smallint,
												   alteration_year smallint,
												   demolition_year smallint,
												   row_hash bytea /*generated always as (digest(concat_ws('|', bin, base_bbl, doitt_id, ground_elevation, height_roof, construction_year, alteration_year, demolition_year, doitt_source), 'sha256')) stored*/,
												   doitt_source varchar(30),
												   overlap_except bit,
												   last_status_type varchar(255),
												   shape geometry);